### ISSUE TITLE
建议: 自动导入图标支持

### ISSUE THREAD

**Issue by hotuns** [dishait/tov-template-lite#1]

**Comment by markthree** [comment]
@hedongshu 其实我想可以尽量使用 `unocss` 的图标规则 👉 [unocss/unocss/tree/main/packages/preset-icons](https://github.com/unocss/unocss/tree/main/packages/preset-icons/)

**Comment by markthree** [comment]
[pr-使用unocss的图标](https://github.com/dishait/tov-template-lite/pull/2)
